### ISSUE TITLE
Failed to add edge detect on GPIO setup after new config received

### ISSUE THREAD

**Issue by phwoelfel** [dgray10/SecPi#10]
```
2015-06-04 11:05:52,808 | INFO:  Registered sensor gpio: 15
Traceback (most recent call last):
  File "worker.py", line 191, in <module>
    w = Worker()
  File "worker.py", line 54, in __init__
    self.channel.start_consuming() # this is a blocking call!!
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 955, in start_consuming
    self.connection.process_data_events()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 240, in process_data_events
    if self._handle_read():
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 348, in _handle_read
    super(BlockingConnection, self)._handle_read()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 351, in _handle_read
    self._on_data_available(data)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 1285, in _on_data_available
    self._process_frame(frame_value)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 1365, in _process_frame
    self._deliver_frame_to_channel(frame_value)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 976, in _deliver_frame_to_channel
    return self._channels[value.channel_number]._handle_content_frame(value)
  File "/usr/local/lib/python2.7/dist-packages/pika/channel.py", line 792, in _handle_content_frame
    self._on_deliver(*response)
  File "/usr/local/lib/python2.7/dist-packages/pika/channel.py", line 886, in _on_deliver
    body)
  File "worker.py", line 110, in got_config
    self.setup_sensors()
  File "worker.py", line 123, in setup_sensors
    GPIO.add_event_detect(int(sensor["gpio"]), GPIO.RISING, callback=self.alarm, bouncetime=5000)       
RuntimeError: Failed to add edge detection
```

**Comment by phwoelfel** [comment]
Hapoened because of same gpio port twice. Maybe just try/catch or add to list upon registering and check if not in list.
