### ISSUE TITLE
Web interface not showing

### ISSUE THREAD

**Issue by majbah-ha** [dgray10/SecPi#119]
web interface start as service , but do not show when  go to https://pi-ip:8443

root@raspberrypi:~# /etc/init.d/secpi-webinterface status
● secpi-webinterface.service - SecPi Webinterface
   Loaded: loaded (/etc/systemd/system/secpi-webinterface.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-09-13 00:59:52 BST; 1s ago
 Main PID: 11539 (python)
    Tasks: 1 (limit: 2059)
   CGroup: /system.slice/secpi-webinterface.service
           └─11539 python /opt/secpi/webinterface/main.py /opt/secpi

Sep 13 00:59:52 raspberrypi systemd[1]: Started SecPi Webinterface.

Got this error when controlling
root@raspberrypi:~# python /opt/secpi/webinterface/main.py /opt/secpi

Traceback (most recent call last):
  File "/opt/secpi/webinterface/main.py", line 356, in <module>
    run()
  File "/opt/secpi/webinterface/main.py", line 338, in run
    cherrypy.tree.mount(Root(), '/', app_config)
  File "/opt/secpi/webinterface/main.py", line 93, in __init__
    self.connect()
  File "/opt/secpi/webinterface/main.py", line 106, in connect
    "keyfile":PROJECT_PATH+"/certs/"+config.get('rabbitmq')['keyfile']
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 643, in __init__
    self.ssl_options = ssl_options
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 491, in ssl_options
    'ssl_options must be None or SSLOptions but got %r' % (value,))
TypeError: ssl_options must be None or SSLOptions but got {'ca_certs': u'/opt/secpi/certs/ca/cacert.pem', 'keyfile': u'/opt/secpi/certs/webui.secpi.local.key.pem', 'certfile': u'/opt/secpi/certs/webui.secpi.local.cert.pem'}

**Comment by Murdock79** [comment]
Have you already solved it? I have the same Problems.
