### ISSUE TITLE
bad file descriptor error with TCP sensor

### ISSUE THREAD

**Issue by phwoelfel** [dgray10/SecPi#29]
following error appears on the worker when the tcp sensor is used:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 236, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 155, in _eintr_retry
    return func(*args)
  File "/usr/lib/python2.7/SocketServer.py", line 455, in fileno
    return self.socket.fileno()
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
```

This happens mostly during debug --> sending new config to the worker multiple times

**Comment by MartinLiebl** [comment]
Not sure if bug still exists, but will not fix
