### ISSUE TITLE
button control using gpiozero

### ISSUE THREAD

**Issue by satishgunjal** [dgray10/SecPi#33]
from gpiozero import LED, Button
from signal import pause

led = LED(2)
button = Button(27)

button.when_pressed = led.on
button.when_released = led.off

pause()

Every time I run above code, for first attempt I get below error and second attempt it works fine!!

Traceback (most recent call last):
File "test.py", line 5, in <module>
button = Button(27)
File "/usr/lib/python2.7/dist-packages/gpiozero/devices.py", line 51, in **call**
result = super(GPIOFixedAttrs, cls).**call**(_args, *_kwargs)
File "/usr/lib/python2.7/dist-packages/gpiozero/input_devices.py", line 405, in **init**
super(Button, self).**init**(pin, pull_up, bounce_time)
File "/usr/lib/python2.7/dist-packages/gpiozero/input_devices.py", line 262, in **init**
bouncetime=-666 if bounce_time is None else int(bounce_time \* 1000)
RuntimeError: Failed to add edge detection

**Comment by phwoelfel** [comment]
You probably have to do a cleanup. With RPi.GPIO there is a cleanup method. See: http://raspi.tv/2013/rpi-gpio-basics-3-how-to-exit-gpio-programs-cleanly-avoid-warnings-and-protect-your-pi
