### ISSUE TITLE
error on initial startup (no sensors in config)

### ISSUE THREAD

**Issue by phwoelfel** [dgray10/SecPi#39]
Traceback (most recent call last):
  File "/opt/secpi/worker/worker.py", line 466, in <module>
    w = Worker()
  File "/opt/secpi/worker/worker.py", line 63, in **init**
    self.setup_sensors()
  File "/opt/secpi/worker/worker.py", line 394, in setup_sensors
    for sensor in config.get("sensors"):
TypeError: 'NoneType' object is not iterable

**Comment by MartinLiebl** [comment]
tested, works now
