### ISSUE TITLE
Error in mailer

### ISSUE THREAD

**Issue by phwoelfel** [dgray10/SecPi#45]
```
2016-01-23 16:09:52,018 [ERROR] manager(345): Error notifying: 'Mailer' object has no attribute 'corrupted'
Traceback (most recent call last):
  File "/opt/secpi/manager/manager.py", line 343, in notify
    notifier.notify(info)
  File "/opt/secpi/manager/mailer.py", line 35, in notify
    if not self.corrupted:
AttributeError: 'Mailer' object has no attribute 'corrupted'
```

**Comment by phwoelfel** [comment]
installation wasn't completly updated --> my fault
