### ISSUE TITLE
Dropbox dependency is missing in requirements.txt

### ISSUE THREAD

**Issue by MartinLiebl** [dgray10/SecPi#84]

**Comment by MartinLiebl** [comment]
2016-04-03 17:43:01,497 [ERROR] Couldn't import module dropbox_dropper: No module named dropbox
Traceback (most recent call last):
  File "/opt/secpi/manager/manager.py", line 165, in class_for_name
    m = importlib.import_module(module_name)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/opt/secpi/manager/dropbox_dropper.py", line 1, in <module>
    import dropbox
ImportError: No module named dropbox
